# ---------------- aliases ----------------
alias 'ls'='exa'
alias 'll'='ls -l'
alias 'project'='cd ~/renga/workspace/renga'
alias 'dcla'='docker container ls -a'
alias 'dsp'='docker system prune --force'
alias 'dl'='docker logs'
alias 'dc'='docker container'
alias 'dslb'='docker service logs -f wa_backend'
alias 'cat'='bat'
# mansion-note
alias 'mn-restart'='~/renga/workspace/renga/bin/restart-wa.sh'
alias 'mn-start'='~/renga/workspace/renga/bin/start-wa.sh'
alias 'mn-stop'='~/renga/workspace/renga/bin/stop-wa.sh'
alias 'mn-init-db'='~/renga/workspace/renga/bin/init-db.sh'
alias 'mn-clear-mem'='~/renga/workspace/renga/bin/clear-memcached.sh'
alias 'mn-compile-js-dev'='~/renga/workspace/renga/mansion-note/webapp/bin/javascript.sh dev'
alias 'mn-compile-js-build'='~/renga/workspace/renga/mansion-note/webapp/bin/javascript.sh build'
alias 'mn-compile-css'='~/renga/workspace/renga/mansion-note/webapp/bin/css.sh'
alias 'mn-load-bukken'='~/renga/workspace/renga/bin/load-bukken.sh'
alias 'mn-deploy-staging-worker'='~/renga/workspace/renga/mansion-note/worker/bin/staging.sh'
alias 'mn-deploy-staging-webapp'='~/renga/workspace/renga/mansion-note/webapp/bin/staging.sh'
alias 'mn-deploy-test1-worker'='~/renga/workspace/renga/mansion-note/worker/bin/test1.sh'
alias 'mn-deploy-test1-webapp'='~/renga/workspace/renga/mansion-note/webapp/bin/test1.sh'
alias 'mn-cd-bin'='~/renga/workspace/renga/bin/'
