# ---------------- aliases ----------------
alias 'ls'='exa'
alias 'll'='ls -l'
alias 'project'='cd ~/renga/workspace/renga'
alias 'dcla'='docker container ls -a'
alias 'dsp'='docker system prune --force'
alias 'dl'='docker logs'
alias 'dc'='docker container'
alias 'dslb'='docker service logs -f wa_backend'
alias 'cat'='bat'